Jenkinsfile, package-lock.json, package.json, src/Page.ts, src/atoms/cta/Button.ts, src/atoms/cta/ContentLink.ts, src/molecules/cta/CtaBlock.ts, src/organisms/hero/Hero.ts, src/organisms/hero/HeroBasic.ts, tslint.json
Added linting rules, jenkins configuration
=> Adds code style checks

package.json, src/atoms/cta/Button.ts, src/atoms/cta/ContentButton.ts
Update button to contentbutton due to html render reserved button name
bump version to 0.0.4
=> fix(button) update button to contentbutton

package.json, src/organisms/hero/Hero.ts
After discussion with UX, cta optional
=> CTA in hero basic optional

package-lock.json, package.json, src/atoms/properties/Property.ts, src/atoms/tooltip/Tooltip.ts, src/molecules/cards/BusinessCard.ts, src/molecules/cards/Card.ts, src/molecules/sections/ResellerSection.ts, src/molecules/sections/Section.ts, src/organisms/overview/Overview.ts
Add models needed for the overview
Add lint:fix FTW
=> feat(overview): add overview modeling

package-lock.json, package.json, src/atoms/media/CraftImage.ts, src/molecules/cards/Card.ts
For resellers, which have their logo provided by craft
=> Add craft image

package.json, src/atoms/limit/Limit.ts, src/molecules/sections/ListSection.ts
Set list limit for large and small screens
=> fix(limit): fix overview list limit

package.json, src/atoms/cta/Link.ts, src/molecules/link-list/LinkList.ts
=> feature(link-list): add link list

package.json, src/molecules/search/Search.ts, src/organisms/page-header/PageHeader.ts
=> feat(header): add page header

package.json, src/atoms/ListHeading/ListHeading.ts, src/atoms/cta/Link.ts, src/molecules/legal-navigation/LegalNavigation.ts, src/molecules/link-list/LinkList.ts, src/molecules/navigation-item/NavigationItem.ts, src/organisms/page-footer/PageFooter.ts, src/organisms/page-header/PageHeader.ts
=> feat(navigationItem): model navigationItem

dist/molecules/contentGeneral/ContentGeneral.d.ts, dist/molecules/contentGeneral/ContentGeneral.js, dist/molecules/contentGeneral/ContentGeneral.js.map, dist/molecules/tab/Tab.d.ts, dist/molecules/tab/Tab.js, dist/molecules/tab/Tab.js.map, dist/organisms/tabbedContent/TabbedContent.d.ts, dist/organisms/tabbedContent/TabbedContent.js, dist/organisms/tabbedContent/TabbedContent.js.map, package-lock.json, package.json, src/molecules/contentGeneral/ContentGeneral.ts, src/molecules/tab/Tab.ts, src/organisms/TabbedContent/TabbedContent.ts, src/organisms/tabbedContent/TabbedContent.ts
Add tabbed content organism
Add content general molecule
Add tab  molecule
=> feat(tabbed): add tabbed content organism

dist/molecules/blocks/ContentBlock.d.ts, dist/molecules/blocks/ContentBlock.js, dist/molecules/blocks/ContentBlock.js.map, dist/molecules/sections/ListSection.d.ts, dist/molecules/sections/ListSection.js.map, package-lock.json, package.json, src/molecules/blocks/ContentBlock.ts, src/molecules/sections/ListSection.ts
Add contentBlocks
Add new build
Update list section
=> feat(contentBlocks): add contentBlocks

dist/organisms/hero/HeroArticle.d.ts, dist/organisms/hero/HeroArticle.js, dist/organisms/hero/HeroArticle.js.map, package-lock.json, package.json, src/organisms/hero/HeroArticle.ts
=> feat(heroArticle): add heroArticle

dist/molecules/article/ArticleAuthor.d.ts, dist/molecules/article/ArticleAuthor.js, dist/molecules/article/ArticleAuthor.js.map, dist/molecules/article/ArticleHeader.d.ts, dist/molecules/article/ArticleHeader.js, dist/molecules/article/ArticleHeader.js.map, dist/organisms/article-content/ArticleContent.d.ts, dist/organisms/article-content/ArticleContent.js.map, package-lock.json, package.json, src/molecules/article/ArticleAuthor.ts, src/molecules/article/ArticleHeader.ts
Add article author
Add article header
=> feat(author): add article author

package-lock.json, package.json
=> Add analytical event to notification

dist/molecules/fields/ComboBoxField.d.ts, dist/molecules/fields/ComboBoxField.js, dist/molecules/fields/ComboBoxField.js.map, dist/molecules/fields/Field.d.ts, dist/molecules/fields/Field.js, dist/molecules/fields/Field.js.map, dist/molecules/fields/SelectBoxField.d.ts, dist/molecules/fields/SelectBoxField.js, dist/molecules/fields/SelectBoxField.js.map, dist/organisms/overview/OverviewResellers.d.ts, dist/organisms/overview/OverviewResellers.js, dist/organisms/overview/OverviewResellers.js.map, dist/organisms/page-footer/PageFooter.d.ts, dist/organisms/preferencebar/PreferenceBar.d.ts, dist/organisms/preferencebar/PreferenceBar.js.map, package-lock.json, package.json, src/molecules/fields/ComboBoxField.ts, src/molecules/fields/Field.ts, src/molecules/fields/SelectBoxField.ts, src/organisms/overview/OverviewResellers.ts, src/organisms/page-footer/PageFooter.ts, src/organisms/preferencebar/PreferenceBar.ts
Story: [UWEB-6527](https://jira.ultimaker.com/browse/UWEB-6527)
Story: [UWEB-8625](https://jira.ultimaker.com/browse/UWEB-6525)
* add(): Fields definition
* add(): ComboBoxField definition
* add(): SelectBoxField definition
* add(): OverviewResellers definition
http://playground-resellers.ultimaker.k8s-dev.ultimaker.works/
=> UWEB-6527: country selector & language selector

dist/organisms/overview/Overview.d.ts, dist/organisms/overview/OverviewResellers.d.ts, dist/organisms/overview/OverviewResellers.js.map, package-lock.json, package.json, src/organisms/overview/Overview.ts, src/organisms/overview/OverviewResellers.ts
Do NOT merge until the branch in Nuxt has been merged
=> feat(reseller empty state): add empty message for resellers overview

dist/atoms/video-source/VideoSource.d.ts, dist/atoms/video-source/VideoSource.js, dist/atoms/video-source/VideoSource.js.map, dist/organisms/hero/HeroHomepage.d.ts, dist/organisms/hero/HeroHomepage.js.map, package-lock.json, package.json, src/atoms/video-source/VideoSource.ts, src/organisms/hero/HeroHomepage.ts
add video to the hero-homepage component
https://playground-hero-video.ultimaker.k8s-dev.ultimaker.works/
=> add(): UWEB-6637 looping video

dist/organisms/article-content/ArticleContent.d.ts, dist/organisms/article-content/ArticleContent.js.map, package-lock.json, package.json, src/organisms/article-content/ArticleContent.ts
make display of social icons at the bottom of articles optional
tbd
=> feature(): uweb 6304 add social icon choice

dist/organisms/form/Form.d.ts, dist/organisms/form/Form.js.map, package-lock.json, package.json, src/organisms/form/Form.ts
[UWEB-7077](https://jira.ultimaker.com/browse/UWEB-7077)
https://playground-input-hidden.ultimaker.k8s-dev.ultimaker.works/materials/pla
=> feature(): InputHidden

dist/organisms/form/InputCheckbox.d.ts, dist/organisms/form/InputCheckbox.js, dist/organisms/form/InputCheckbox.js.map, package-lock.json, package.json, src/organisms/form/InputCheckbox.ts
https://playground-checkbox-hidden.ultimaker.k8s-dev.ultimaker.works/materials/pla
=> feature(): UWEB-7078 checkbox

dist/organisms/form/InputCheckboxes.d.ts, dist/organisms/form/InputCheckboxes.js, dist/organisms/form/InputCheckboxes.js.map, package-lock.json, package.json, src/organisms/form/InputCheckboxes.ts
[UWEB-7094](https://jira.ultimaker.com/browse/UWEB-7094)
https://playground-checkboxes.ultimaker.k8s-dev.ultimaker.works/materials/pla
* https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/338
* https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/234
=> feature(): UWEB-7094 checkboxes

dist/molecules/wizard/Wizard.d.ts, dist/molecules/wizard/Wizard.js.map, src/molecules/wizard/Wizard.ts
[UWEB-7120](https://jira.ultimaker.com/browse/UWEB-7120)
https://playground-data-continuity.ultimaker.k8s-dev.ultimaker.works/materials/pla
https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/235
https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/340
=> feature(): UWEB-7120 data continuity

dist/organisms/form/Form.d.ts, dist/organisms/form/Form.js.map, package-lock.json, package.json, src/organisms/form/Form.ts
[UWEB-7121](https://jira.ultimaker.com/browse/UWEB-7121)
https://playground-form-analytics.ultimaker.k8s-dev.ultimaker.works/materials/pla
https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/237
https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/341
=> feature(): UWEB-7121 form analytics

dist/organisms/form/Form.d.ts, dist/organisms/form/Form.js.map, package-lock.json, package.json, src/organisms/form/Form.ts
[UWEB-7080](https://jira.ultimaker.com/browse/UWEB-7080)
https://playground-form-fieldsets.ultimaker.k8s-dev.ultimaker.works/materials/pla
https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/343
https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/239
=> feature(): UWEB-7080 fieldsets

dist/molecules/cards/CardArticle.d.ts, dist/molecules/cards/CardArticle.js.map, package-lock.json, package.json, src/molecules/cards/CardArticle.ts
[UWEB-7185](https://jira.ultimaker.com/browse/UWEB-7185)
https://playground-card-article.ultimaker.k8s-dev.ultimaker.works/learn
scroll down to _Download free white papers_
https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/249
https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/345
=> feature(): UWEB-7185 card article subtitle

dist/organisms/hero/HeroArticle.d.ts, dist/organisms/hero/HeroArticle.js.map, package-lock.json, package.json, src/organisms/hero/HeroArticle.ts
[UWEB-6619](https://jira.ultimaker.com/browse/UWEB-6619)
https://playground-estimated.ultimaker.k8s-dev.ultimaker.works/learn/zeiss-precision-parts-for-serial-production
https://playground-estimated.ultimaker.k8s-dev.ultimaker.works/learn/3d-printer-emissions-and-indoor-air-quality
https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/250
https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/346
=> feature(): UWEB-6619 article estimated reading

dist/molecules/article/ArticleImage.d.ts, dist/molecules/article/ArticleImage.js.map, package-lock.json, package.json, src/molecules/article/ArticleImage.ts
[UWEB-6381](https://jira.ultimaker.com/browse/UWEB-6381)
https://playground-aspect-ratio.ultimaker.k8s-dev.ultimaker.works/learn/zeiss-precision-parts-for-serial-production
https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/347
https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/258
=> feature(): UWEB-6381 aspect ratios

dist/organisms/article-image-group/ArticleImageGroup.d.ts, dist/organisms/article-image-group/ArticleImageGroup.js, dist/organisms/article-image-group/ArticleImageGroup.js.map, package-lock.json, package.json, src/organisms/article-image-group/ArticleImageGroup.ts
[UWEB-6086](https://jira.ultimaker.com/browse/UWEB-6086)
https://playground-article-image-group.ultimaker.k8s-dev.ultimaker.works/learn/heineken-ensuring-production-continuity-with-3d-printing
https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/348
https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/261
=> feature(): UWEB-6086 image group

dist/organisms/quote/Quote.d.ts, package-lock.json, package.json, src/organisms/quote/Quote.ts
I changed the path to make the import actually work
=> Fix quote ts import

dist/Meta.d.ts, dist/Meta.js.map, package-lock.json, package.json, src/Meta.ts
=> feature(): UWEB-7346 robots

dist/atoms/link/Link.d.ts, dist/atoms/link/Link.js.map, dist/organisms/flyout/FlyoutItem.d.ts, dist/organisms/flyout/FlyoutItem.js.map, package-lock.json, package.json, src/atoms/link/Link.ts, src/organisms/flyout/FlyoutItem.ts
[UWEB-7392](https://jira.ultimaker.com/browse/UWEB-7392)
https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/291
https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/372
https://playground-flyout-support.ultimaker.k8s-dev.ultimaker.works/
=> refactor(): Flyout mapping of Link

dist/organisms/flyout/FlyoutItem.d.ts, dist/organisms/flyout/FlyoutItem.js.map, package-lock.json, package.json, src/organisms/flyout/FlyoutItem.ts
[UWEB-7392](https://jira.ultimaker.com/browse/UWEB-7392)
https://github.com/Ultimaker/ultimaker.com-frontend-nuxt/pull/292
https://github.com/Ultimaker/Ultimaker.com-integration-service/pull/373
https://playground-flyout-followup.ultimaker.k8s-dev.ultimaker.works/
=> follow-up(): UWEB-7392
